import {collections,filterItems,isFresh} from './catalog.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen=n=>'¥'+n.toLocaleString('ja-JP');
const brand='<span class="brand-mark" aria-hidden="true">贈</span><span>贈りもの帖<small>OKURIMONO CHO</small></span>';
export function shell({title,description,path='/',body,noindex=false,origin='https://gift.jev.jp'}) {return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | 贈りもの帖</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow'}"><link rel="canonical" href="${origin}${path}"><meta property="og:title" content="${esc(title)} | 贈りもの帖"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}${path}"><meta property="og:locale" content="ja_JP"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#main">本文へ移動</a><div class="topline">誰かを想う、その時間も贈りもの。</div><header><a class="brand" href="/" aria-label="贈りもの帖 ホーム">${brand}</a><nav aria-label="メインナビゲーション"><a href="/#collections">ギフトを探す</a><a href="/guide">選び方のヒント</a><a href="/about" class="nav-about">このサイトについて</a></nav></header>${body}<footer><div class="footer-top"><a class="brand" href="/">${brand}</a><p>気持ちに合うものを、無理のない予算で。</p></div><div class="footer-links"><a href="/about">運営・広告について</a><a href="/privacy">プライバシー</a><a href="/guide">ギフト選びのヒント</a><a href="https://webservice.rakuten.co.jp/" rel="noopener noreferrer" target="_blank">Supported by Rakuten Developers</a></div><p class="fine">当サイトは楽天アフィリエイトを利用しています。リンク経由の購入により運営者に報酬が発生する場合があります。<br>商品情報・画像は楽天市場の提供情報です。価格・在庫・送料・配送日・包装条件は、販売店の最新情報をご確認ください。</p><div class="copyright">© ${new Date().getFullYear()} 贈りもの帖<span>A SMALL GIFT, A GOOD DAY.</span></div></footer></body></html>`;}
function cards(items,fresh) {return items.map((i,n)=>`<article class="product"><a class="product-image" href="${esc(i.url)}" target="_blank" rel="sponsored noopener noreferrer" aria-label="${esc(i.title)}を楽天市場で見る（広告・新しいタブ）"><img src="${esc(i.image)}" alt="${esc(i.title)}" width="360" height="360" ${n<4?'fetchpriority="high"':'loading="lazy"'}><span class="image-label">RAKUTEN ICHIBA</span></a><div class="product-info"><div class="product-meta">${i.freeShipping?'送料込み':'送料は販売店で確認'}<span>PR</span></div><h3><a href="${esc(i.url)}" target="_blank" rel="sponsored noopener noreferrer">${esc(i.title)}</a></h3><p class="shop">${esc(i.shop)}</p><div class="product-bottom"><strong>${fresh?yen(i.price):'価格は販売店で確認'}${fresh?'<small>税込</small>':''}</strong>${i.reviews?`<span class="rating"><span aria-hidden="true">★</span> ${i.rating.toFixed(2)} <small>(${i.reviews.toLocaleString('ja-JP')})</small></span>`:'<span class="rating">レビューなし</span>'}</div><a class="shop-link" href="${esc(i.url)}" target="_blank" rel="sponsored noopener noreferrer">楽天市場で詳しく見る <span aria-hidden="true">↗</span></a></div></article>`).join('');}
export function catalogPage(c,catalog,url,origin) {
 const home=url.pathname==='/'; const fresh=isFresh(catalog);const all=catalog?.items||[];const items=filterItems(all,url.searchParams);
 const budget=Number(url.searchParams.get('budget'))||0;
 const update=catalog?new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(new Date(catalog.updatedAt)):'';
 const selected=all[0];
 const hero=home?`<section class="intro"><div><div class="eyebrow">THE GIFT EDIT · 日々の贈りもの案内</div><h1>あの人を想う。<br>贈りものが、<em>見つかる。</em></h1><p>小さなお礼も、特別なお祝いも。<br>気持ちにちょうどいいひと品を、予算から。</p><div class="occasion-links"><a href="/collections/sweets?budget=3000">ちょっとしたお礼</a><a href="/collections/home?budget=5000">新生活のお祝い</a><a href="/collections/flowers?budget=10000">大切な記念日</a></div></div><aside class="hero-note"><div class="note-index">A GIFT TO SAY THANK YOU <span>01 / 06</span></div>${selected?`<a href="${esc(selected.url)}" target="_blank" rel="sponsored noopener noreferrer"><img src="${esc(selected.image)}" alt="${esc(selected.title)}" width="360" height="280"><span class="hero-caption">お礼に添える、甘いひと箱。<small>お菓子のコレクションから · PR</small></span></a>`:'<p>気持ちが伝わる、ひと品を。</p>'}</aside></section>`:`<div class="breadcrumbs"><a href="/">ホーム</a><span>/</span>${c.name}</div><section class="collection-intro"><div class="eyebrow">COLLECTION ${c.number} · ${c.en}</div><h1>${c.intro}</h1><p>${c.description}</p></section>`;
 const tabs=`<div id="collections" class="section-top"><h2>気持ちに合うギフトを探す</h2><span>THE COLLECTIONS</span></div><nav class="collections" aria-label="ギフトのジャンル">${collections.map(x=>`<a href="/collections/${x.id}" ${x.id===c.id?'aria-current="page"':''}><small>${x.number}</small>${x.short}</a>`).join('')}</nav>`;
 const form=`<form class="filters" method="get" action="${home?'/':'/collections/'+c.id}#results"><fieldset><legend>ご予算 <span>商品価格・税込</span></legend><div class="budget-options">${[[0,'すべて'],[3000,'3,000円まで'],[5000,'5,000円まで'],[10000,'10,000円まで']].map(([v,t])=>`<label><input type="radio" name="budget" value="${v}" ${v===budget?'checked':''}><span>${t}</span></label>`).join('')}</div></fieldset><div class="filter-secondary"><label class="shipping"><input type="checkbox" name="shipping" value="free" ${url.searchParams.get('shipping')==='free'?'checked':''}>送料込みのみ</label><label class="sort-label">並び順<select name="sort"><option value="standard">楽天の標準順</option><option value="price" ${url.searchParams.get('sort')==='price'?'selected':''}>価格が安い順</option><option value="reviews" ${url.searchParams.get('sort')==='reviews'?'selected':''}>レビュー件数順</option></select></label><button type="submit">条件を適用</button></div></form>`;
 const products=`<section id="results" aria-label="商品一覧"><div class="results-head"><div><span class="eyebrow">${c.en}</span><h2>${c.name}<span>${items.length}<small>件</small></span></h2></div><p>${update?'情報取得 '+update+' JST':'商品情報を準備中'}<br>広告・アフィリエイトリンクを含みます</p></div><p class="source-note">楽天市場から取得した最大30件内で絞り込みます。掲載商品は実使用レビュー・全商品の比較ではありません。${fresh?'':' 最新の価格は販売店でご確認ください。'}</p>${items.length?`<div class="products">${cards(items,fresh)}</div>`:`<div class="empty"><h3>${all.length?'この条件のギフトは、まだ見つかりませんでした。':'商品情報を取得できませんでした。'}</h3><p>${all.length?'予算を広げるか、送料の条件を外して探してみてください。':'しばらくしてから、もう一度お試しください。'}</p><a href="/collections/${c.id}">条件をリセット</a></div>`}</section>`;
 const tip=`<aside class="tip"><span class="tip-number">A LITTLE<br>THOUGHT</span><div><h2>贈る前に、ひとつだけ。</h2><p>${c.tip}</p><a href="/guide">ギフト選びのヒントを読む</a></div></aside>`;
 return shell({title:home?'予算と気持ちで選ぶ、日々のギフト':c.name+'のギフトを予算から探す',description:home?'お礼や記念日、新生活のお祝いに。お菓子、コーヒー、暮らしの道具など、楽天市場のギフトを予算と送料から探せます。':c.description,path:home?'/':'/collections/'+c.id,noindex:!!url.search,origin,body:`<main id="main">${hero}${tabs}${form}${products}${tip}</main>`});
}
const pages={
 about:{title:'運営・広告について',intro:'選ぶ時間を、少し心地よく。',content:`<h2>贈りもの帖について</h2><p>贈りもの帖は、お礼やお祝いのギフトを、ジャンル・予算・送料から探せる個人運営のサイトです。楽天市場に掲載された商品の情報を、楽天ウェブサービスから取得して紹介しています。</p><h2>商品を掲載する基準</h2><p>ジャンルごとに決めた検索語を使い、商品価格1,000〜30,000円・在庫あり・画像ありの条件で最大30件を取得しています。初期表示は楽天の標準順です。比較できるのは取得した商品の範囲に限られ、市場全体の最安値や品質を保証するものではありません。</p><p>商品のレビュー点数と件数は楽天市場の情報です。運営者が商品を使用・評価した点数ではありません。購入者のレビュー文章の生成や、根拠のないおすすめ順位付けは行っていません。</p><h2>広告・アフィリエイトについて</h2><p>当サイトは楽天アフィリエイトに参加しています。「PR」と表示した商品リンクから購入されると、運営者が報酬を受け取る場合があります。報酬率による並べ替えは行っていません。</p><h2>更新と購入について</h2><p>商品情報は6時間ごとの更新を予定しています。通信障害などで更新が遅れる場合があり、24時間以上経過した情報では価格を表示しません。最終的な価格・在庫・送料・納期・包装・返品条件は、購入先の販売店でご確認ください。注文と決済は販売店で行われます。</p><h2>運営・お問い合わせ</h2><p>運営：siren2345（個人運営）<br>サイトの不具合・掲載内容に関するお問い合わせは、<a href="https://github.com/siren2345/okurimono-cho/issues" target="_blank" rel="noopener noreferrer">GitHubの問い合わせ窓口</a>へお寄せください（GitHubアカウントが必要です）。注文に関するお問い合わせは購入先の販売店へお願いします。公開窓口のため、注文番号や個人情報は記入しないでください。</p>`},
 privacy:{title:'プライバシーについて',intro:'必要な情報だけを扱います。',content:`<h2>このサイトで扱う情報</h2><p>当サイトには会員登録、決済、お問い合わせフォームはありません。ギフトの絞り込み条件はURLに反映されます。氏名、住所、メールアドレスを入力する必要はありません。</p><h2>アクセスと外部サービス</h2><p>サイトの配信にはCloudflareを利用しています。通信時にIPアドレス、ブラウザ情報、アクセス先URLなどがCloudflareによって処理される場合があります。運営者は障害調査のため、サンプリングされた運用ログを確認する場合があります。独自の広告トラッカーやアクセス解析タグは設置していません。</p><p>商品画像は楽天のサーバーから読み込まれるため、画像表示の際にIPアドレスなどの通信情報が楽天側に送信されます。ブラウザの参照元情報は送らない設定にしています。</p><h2>アフィリエイトリンク</h2><p>商品リンクを開くと楽天のサイトへ移動します。移動先では購入の成果計測などのためにCookie等が利用される場合があります。詳しくは<a href="https://privacy.rakuten.co.jp/" target="_blank" rel="noopener noreferrer">楽天グループのプライバシーポリシー</a>と<a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Cloudflareのプライバシーポリシー</a>をご確認ください。</p><h2>お問い合わせ</h2><p>プライバシーに関するお問い合わせは<a href="/about">運営・広告について</a>の窓口をご利用ください。</p><p>制定日：2026年10月7日</p>`},
 guide:{title:'ギフト選びのヒント',intro:'値段より先に、相手の一日を思い浮かべる。',content:`<h2>01　使う場面から考える</h2><p>仕事の合間にひと息つく人なら、個包装のお菓子やドリップコーヒー。新しい暮らしを始める人なら、毎日使うタオル。相手がいつ、どこで、どう使うかを想像すると、選択肢を絞りやすくなります。</p><a class="text-link" href="/collections/coffee">コーヒーのギフトを見る</a><h2>02　予算は送料・包装代まで含めて</h2><p>当サイトの予算フィルターは商品価格（税込）が基準です。送料や包装代が別にかかる場合は、合計額が予算を超えることもあります。購入する前に販売店の注文画面で確かめましょう。</p><a class="text-link" href="/collections/sweets?budget=3000">3,000円までのお菓子を見る</a><h2>03　好みがわからないときは</h2><p>食べものならアレルギーや苦手な食材を確認。香りや色へのこだわりがわからないときは、相手が選べるカタログギフトも一案です。ただし、申込方法や有効期限が相手にとって負担にならないかも考えましょう。</p><a class="text-link" href="/collections/catalog">選べるギフトを見る</a><h2>04　受け取るところまでが贈りもの</h2><p>冷凍食品なら冷凍庫の空き、花なら飾る場所、大きな箱なら持ち帰りやすさも大切です。「在庫あり」は希望日への配送を保証しません。お届け先・注文時刻によって変わるため、日付指定や包装対応を販売店で確認してください。</p><h2>贈る前のチェック</h2><ul><li>相手の苦手なものやアレルギーを確認した</li><li>送料・包装代を含めて予算内に収まる</li><li>賞味期限・保存方法・サイズを確認した</li><li>配送日・ラッピング・のしの条件を確認した</li><li>メッセージを添える方法を確認した</li></ul>`}
};
export function infoPage(id,origin){const p=pages[id];if(!p)return null;return shell({title:p.title,description:p.intro,path:'/'+id,origin,body:`<main id="main" class="prose"><a class="back" href="/">贈りもの帖 ホーム</a><div class="eyebrow">OKURIMONO JOURNAL</div><h1>${p.title}</h1><p class="lead">${p.intro}</p>${p.content}</main>`});}
export function notFound(origin){return shell({title:'ページが見つかりません',description:'ギフトを探すトップページへお戻りください。',noindex:true,origin,body:'<main id="main" class="prose"><h1>ページが見つかりません</h1><p>お探しのページは移動したか、存在しません。</p><a href="/">ギフトを探す</a></main>'});}
